In [2]:
#recurssion
def fib(n):
    if n==1:
        return 1
    elif n==2:
        return 1
    return fib(n-1) + fib(n-2)

print(fib(10))

55


In [5]:
#fib(500)?

In [8]:
#concatinate
a = [10, 20, 30]
b = [40, 50, 60]
c= a + b
print (c[::-1])

[60, 50, 40, 30, 20, 10]


In [9]:
#loop
for i in c:
    print(i)


10
20
30
40
50
60


In [11]:
for i in range(len(c)):
    print (c[i])

10
20
30
40
50
60


In [12]:
i = 0
while i <len(c):
    print(c[i])
    i+=1

10
20
30
40
50
60


In [25]:
#Dictionary

a ={1:'Deer',2:'Dog', 3:c, 4:{1: 'Cat', 2:b}}

print(a)
print(a.keys())
print(a[4][2][1])

{1: 'Deer', 2: 'Dog', 3: [10, 20, 30, 40, 50, 60], 4: {1: 'Cat', 2: [40, 50, 60]}}
dict_keys([1, 2, 3, 4])
50


In [1]:
import numpy as np

a = np.array([20,30,60])
b = np.array([70,80,90])

a+b

array([ 90, 110, 150])

In [5]:
m= np.array([[20,30,60],[70,80,90]])
n= np.array([[10,30,130],[70,40,80]])
m+n

array([[ 30,  60, 190],
       [140, 120, 170]])

In [10]:
k= np.array([10,30,130,70,40,80])
print(np.reshape(k, [2,3]))
print(np.reshape(k, [3,2]))
print(k.flatten())

[[ 10  30 130]
 [ 70  40  80]]
[[ 10  30]
 [130  70]
 [ 40  80]]
[ 10  30 130  70  40  80]


In [15]:
print(np.zeros([10,10]))
print(np.ones([10,10]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
print(np.random.rand(5,5))
np.random.randint(10,25, size=(10,5))

[[0.33432299 0.28413854 0.37693787 0.86598836 0.68099511]
 [0.02540262 0.32306081 0.08901406 0.90637729 0.3938647 ]
 [0.01121079 0.17855748 0.6627006  0.58461904 0.80510074]
 [0.72502767 0.2083735  0.32037944 0.47969135 0.93623782]
 [0.94687389 0.40015662 0.76715781 0.63472468 0.66058882]]


array([[19, 13, 23, 13, 16],
       [16, 17, 12, 23, 22],
       [15, 20, 12, 16, 21],
       [20, 22, 19, 10, 14],
       [12, 11, 22, 13, 19],
       [24, 14, 16, 23, 16],
       [11, 16, 20, 18, 16],
       [17, 20, 15, 14, 20],
       [16, 12, 20, 24, 24],
       [12, 16, 16, 20, 20]])

In [24]:
k= np.array([10,30,130,70,40,80])
np.where(k==30)
np.sort(k)

array([ 10,  30,  40,  70,  80, 130])

In [28]:
print(np.hstack((k,np.sort(k))))
print(np.vstack((k,np.sort(k))))

[ 10  30 130  70  40  80  10  30  40  70  80 130]
[[ 10  30 130  70  40  80]
 [ 10  30  40  70  80 130]]


In [35]:
#layer of zeroes, used for maintaining the dimensions
np.pad(np.random.randint(10,25, size=(10,5)),([1,0],[1,1]))

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 18, 21, 13, 23, 12,  0],
       [ 0, 24, 13, 22, 20, 21,  0],
       [ 0, 22, 14, 17, 19, 11,  0],
       [ 0, 18, 10, 11, 18, 24,  0],
       [ 0, 19, 20, 12, 19, 20,  0],
       [ 0, 20, 16, 18, 14, 13,  0],
       [ 0, 21, 11, 17, 23, 14,  0],
       [ 0, 17, 21, 10, 17, 22,  0],
       [ 0, 22, 13, 22, 23, 19,  0],
       [ 0, 11, 10, 17, 24, 10,  0]])

In [40]:
#Regression, using numpy functions
x= np.array([2,3,4,5,6,7,8])
y= np.array([4,6,8,25,36,49,64])

np.polyfit(x,y,1)

array([ 10.5       , -25.07142857])