In [22]:
import numpy as np

In [40]:
a = np.random.uniform(9, 30, 2)
b = np.random.uniform(12, 30, 2)
m = np.array((a,b))
m

array([[29.9300847 , 21.74313552],
       [17.88615397, 26.4962795 ]])

In [41]:
print(np.mean(a),np.std(a))

25.836610105424292 4.093474589981163


In [42]:
np.cov(m)# matrix

array([[ 33.51306844, -35.24533011],
       [-35.24533011,  37.0671309 ]])

In [43]:
c = np.random.uniform(13, 30, 2)
d = np.random.uniform(10, 30, 2)
n = np.array((c,d))
n.T

array([[14.00762745, 11.0707554 ],
       [25.87876766, 12.66526135]])

In [44]:
m_mult = np.matmul(m,n)
m_mult

array([[ 659.96241079, 1049.93620167],
       [ 543.87641059,  798.45392747]])

In [46]:
import gzip as gz
i_file = gz.open("t10k-labels-idx1-ubyte.gz", "rb")
contents = i_file.read()

print(contents)

b"\x00\x00\x08\x01\x00\x00'\x10\x07\x02\x01\x00\x04\x01\x04\t\x05\t\x00\x06\t\x00\x01\x05\t\x07\x03\x04\t\x06\x06\x05\x04\x00\x07\x04\x00\x01\x03\x01\x03\x04\x07\x02\x07\x01\x02\x01\x01\x07\x04\x02\x03\x05\x01\x02\x04\x04\x06\x03\x05\x05\x06\x00\x04\x01\t\x05\x07\x08\t\x03\x07\x04\x06\x04\x03\x00\x07\x00\x02\t\x01\x07\x03\x02\t\x07\x07\x06\x02\x07\x08\x04\x07\x03\x06\x01\x03\x06\t\x03\x01\x04\x01\x07\x06\t\x06\x00\x05\x04\t\t\x02\x01\t\x04\x08\x07\x03\t\x07\x04\x04\x04\t\x02\x05\x04\x07\x06\x07\t\x00\x05\x08\x05\x06\x06\x05\x07\x08\x01\x00\x01\x06\x04\x06\x07\x03\x01\x07\x01\x08\x02\x00\x02\t\t\x05\x05\x01\x05\x06\x00\x03\x04\x04\x06\x05\x04\x06\x05\x04\x05\x01\x04\x04\x07\x02\x03\x02\x07\x01\x08\x01\x08\x01\x08\x05\x00\x08\t\x02\x05\x00\x01\x01\x01\x00\t\x00\x03\x01\x06\x04\x02\x03\x06\x01\x01\x01\x03\t\x05\x02\t\x04\x05\t\x03\t\x00\x03\x06\x05\x05\x07\x02\x02\x07\x01\x02\x08\x04\x01\x07\x03\x03\x08\x08\x07\t\x02\x02\x04\x01\x05\t\x08\x07\x02\x03\x00\x04\x04\x02\x04\x01\t\x05\x07\x07\